# Generated by Django 4.2.6 on 2024-07-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jsondata',
            table='regressionModel',
        ),
    ]
