# Generated by Django 4.2.6 on 2024-07-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classificationmodel_alter_regressionmodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassificationModel',
        ),
    ]
